version: '3.1'

# a stack-file version of this for running in Swarm services

services:
  node:
    # reminder, don't use latest tag in production, use versions created by CI/CD
    image: bretfisher/node-docker-good-defaults:latest
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - MONGO_USERNAME_FILE=/run/secrets/mongo_root
      - MONGO_PASSWORD_FILE=/run/secrets/mongo_root_password
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE_NAME=example-database
    secrets:
      - mongo_root
      - mongo_root_password
    deploy:
      replicas: 2

secrets:
  mongo_root:
    external: true
  mongo_root_password:
    external: true
